name: mhu_dart_model
version: 1.0.2-dev
description: Common models
repository: https://github.com/maprohu/mhu_dart_model

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  mhu_dart_commons:
    path: ../mhu_dart_commons
  mhu_dart_proto:
    path: ../mhu_dart_proto
  mhu_dart_builder:
    path: ../mhu_dart_builder

dependencies:
  protobuf: ^3.0.0
  fast_immutable_collections: ^9.1.5
  fixnum: ^1.1.0

  mhu_dart_proto: ^1.0.1
  mhu_dart_commons: ^1.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mhu_dart_builder: ^1.0.1

