name: mhu_dart_model_example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependency_overrides:
  mhu_dart_commons:
    path: ../../mhu_dart_commons
  mhu_dart_proto:
    path: ../../mhu_dart_proto
  mhu_dart_builder:
    path: ../../mhu_dart_builder
  mhu_dart_sourcegen:
    path: ../../mhu_dart_sourcegen
  mhu_dart_pbgen:
    path: ../../mhu_dart_pbgen
  mhu_dart_annotation:
    path: ../../mhu_dart_annotation

dependencies:

  mhu_dart_commons: ^1.0.8
  mhu_dart_proto: ^1.0.3
  mhu_dart_model:
    path: ..
  fixnum: ^1.1.0
  protobuf: ^3.1.0



dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.4.6
  mhu_dart_pbgen: ^1.0.0
  flutter_lints: ^2.0.0

