name: TEST

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
      - run: sudo apt-get install -y protobuf-compiler
      - run: dart pub global activate protoc_plugin
      - run: dart pub get
      - run: dart tool/run_protoc.dart
      - run: dart pub publish --dry-run